[[headers]]
for = "/rss.xml"

[headers.values]
Access-Control-Allow-Origin = "*"


[build]
command = "bun install && bun run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

# Redirects configuration to prevent adapter errors
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
